name: cadet_workshop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gitpython
  - jupyterlab
  - jupyter
  - jupytext
  - pre-commit
  - openpyxl
  - cadet
  - pip
  - pip:
    - "git+https://github.com/fau-advanced-separations/CADET-Process.git@dev"
    - nbtoolbelt
    - jupyterlab_myst
    - jupyterlab_deck
    - ipympl
    - ipywidgets
